<?php

namespace models;

class SupportGroup extends \core\Model
{
    private $id;
    private $name;
    private $type;
    private $facilitator;
    private $co_facilitator;

    public function loadSupportGroupsList()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}